export const APPLICATION_STATUSES = Object.freeze({
  SUBMITTED: "submitted",
  IN_REVIEW: "in_review",
  SHORTLISTED: "shortlisted",
  INTERVIEW: "interview",
  OFFER: "offer",
  REJECTED: "rejected",
  HIRED: "hired",
});

export const APPLICATION_STATUS_VALUES = Object.freeze(
  Object.values(APPLICATION_STATUSES),
);

export const APPLICATION_STATUS_TRANSITIONS = Object.freeze({
  [APPLICATION_STATUSES.SUBMITTED]: Object.freeze([
    APPLICATION_STATUSES.IN_REVIEW,
    APPLICATION_STATUSES.SHORTLISTED,
    APPLICATION_STATUSES.INTERVIEW,
    APPLICATION_STATUSES.OFFER,
    APPLICATION_STATUSES.REJECTED,
  ]),
  [APPLICATION_STATUSES.IN_REVIEW]: Object.freeze([
    APPLICATION_STATUSES.SHORTLISTED,
    APPLICATION_STATUSES.INTERVIEW,
    APPLICATION_STATUSES.OFFER,
    APPLICATION_STATUSES.REJECTED,
  ]),
  [APPLICATION_STATUSES.SHORTLISTED]: Object.freeze([
    APPLICATION_STATUSES.INTERVIEW,
    APPLICATION_STATUSES.OFFER,
    APPLICATION_STATUSES.HIRED,
    APPLICATION_STATUSES.REJECTED,
  ]),
  [APPLICATION_STATUSES.INTERVIEW]: Object.freeze([
    APPLICATION_STATUSES.SHORTLISTED,
    APPLICATION_STATUSES.OFFER,
    APPLICATION_STATUSES.HIRED,
    APPLICATION_STATUSES.REJECTED,
  ]),
  [APPLICATION_STATUSES.OFFER]: Object.freeze([
    APPLICATION_STATUSES.HIRED,
    APPLICATION_STATUSES.REJECTED,
  ]),
  [APPLICATION_STATUSES.REJECTED]: Object.freeze([]),
  [APPLICATION_STATUSES.HIRED]: Object.freeze([]),
});

export const canTransitionApplicationStatus = (currentStatus, nextStatus) =>
  APPLICATION_STATUS_TRANSITIONS[currentStatus]?.includes(nextStatus) ?? false;
