export const APPLICATION_STATUSES = Object.freeze({
  SUBMITTED: "submitted",
  IN_REVIEW: "in_review",
  SHORTLISTED: "shortlisted",
  INTERVIEW: "interview",
  OFFER: "offer",
  REJECTED: "rejected",
  HIRED: "hired",
});

export const APPLICATION_STATUS_VALUES = Object.freeze(
  Object.values(APPLICATION_STATUSES),
);

export const APPLICATION_STATUS_OPTIONS = Object.freeze([
  { label: "Submitted", value: APPLICATION_STATUSES.SUBMITTED },
  { label: "In Review", value: APPLICATION_STATUSES.IN_REVIEW },
  { label: "Shortlisted", value: APPLICATION_STATUSES.SHORTLISTED },
  { label: "Interview", value: APPLICATION_STATUSES.INTERVIEW },
  { label: "Offer", value: APPLICATION_STATUSES.OFFER },
  { label: "Rejected", value: APPLICATION_STATUSES.REJECTED },
  { label: "Hired", value: APPLICATION_STATUSES.HIRED },
]);

export const APPLICATION_STATUS_TRANSITIONS = Object.freeze({
  [APPLICATION_STATUSES.SUBMITTED]: Object.freeze([
    APPLICATION_STATUSES.IN_REVIEW,
    APPLICATION_STATUSES.SHORTLISTED,
    APPLICATION_STATUSES.INTERVIEW,
    APPLICATION_STATUSES.OFFER,
    APPLICATION_STATUSES.REJECTED,
  ]),
  [APPLICATION_STATUSES.IN_REVIEW]: Object.freeze([
    APPLICATION_STATUSES.SHORTLISTED,
    APPLICATION_STATUSES.INTERVIEW,
    APPLICATION_STATUSES.OFFER,
    APPLICATION_STATUSES.REJECTED,
  ]),
  [APPLICATION_STATUSES.SHORTLISTED]: Object.freeze([
    APPLICATION_STATUSES.INTERVIEW,
    APPLICATION_STATUSES.OFFER,
    APPLICATION_STATUSES.HIRED,
    APPLICATION_STATUSES.REJECTED,
  ]),
  [APPLICATION_STATUSES.INTERVIEW]: Object.freeze([
    APPLICATION_STATUSES.SHORTLISTED,
    APPLICATION_STATUSES.OFFER,
    APPLICATION_STATUSES.HIRED,
    APPLICATION_STATUSES.REJECTED,
  ]),
  [APPLICATION_STATUSES.OFFER]: Object.freeze([
    APPLICATION_STATUSES.HIRED,
    APPLICATION_STATUSES.REJECTED,
  ]),
  [APPLICATION_STATUSES.REJECTED]: Object.freeze([]),
  [APPLICATION_STATUSES.HIRED]: Object.freeze([]),
});
